### ISSUE TITLE
Delete and Pull · cmd ⌫ on artboard causes sketch crash

### ISSUE THREAD

**Issue by rockitbaby** [getflourish/Sketch-Mate#13]
steps to reproduce:
- create artboard
- select artboard
- hit [CDM] + [BACKSPACE]
- hit [A]
- drag to create new artboard

demo:
https://www.dropbox.com/s/ab6lyw7vjtt3zlw/sketch_sketch%20crash_20151104.mov?dl=0

**Comment by getflourish** [comment]
Can’t reproduce anymore in 3.6. Let me know if that’s still an issue with the latest version of the plugin. :)

**Comment by getflourish** [comment]
Oops, I was confusing it with "remove artboard". You’re right, "delete and pull" is broken. Looking into it.

**Comment by getflourish** [comment]
Fixed

**Comment by rockitbaby** [comment]
thanks!
