### ISSUE TITLE
Smart Align H & V and multiple selections

### ISSUE THREAD

**Issue by RaphyRaph** [getflourish/Sketch-Mate#15]
Smart align horizontally and vertically should work with more than 2 selected objects.

**Comment by BramEsposito** [comment]
Looks like Smart Align Right works? 

![Smart Align Right](http://i.giphy.com/3oEjHE4ORS2e6KkjYI.gif)

Are you still having this issue?

**Comment by RaphyRaph** [comment]
Please look at the original comment, I was talking about _vertical_ and _horizontal_ align.

**Comment by Vpr99** [comment]
@RaphyRaph took a stab at fixing it. Seems to work for me, but I haven't done any real testing. https://github.com/getflourish/Sketch-Mate/pull/29

**Comment by megaroeny** [comment]
I just came across this issue and stinks that it is an issue. I would help with fixing if I knew how to code this stuff. ☹️

**Comment by BramEsposito** [comment]
@jaminroe I'll try fixing it if you can explain what does not work for you. Can you provide an explanation (before vs after) and expected result. Please also add your sketch version and maybe an example sketch file?

**Comment by megaroeny** [comment]
I tried vertical with more than 2 objects and it says "Please select layer"

Sketch 41

I used the keyboard shortcut for Smart Vertical Align for this recording:
![dec-14-2016 13-48-01](https://cloud.githubusercontent.com/assets/1559447/21195961/f946457c-c203-11e6-90a3-57127065fa07.gif)

**Comment by megaroeny** [comment]
Please see updated comment with GIF above ☝️

**Comment by BramEsposito** [comment]
I wrote a fix and asked @getflourish to review and merge.

You can try [my fork](https://github.com/BramEsposito/Sketch-Mate) if you are in a hurry

Let me know if that fixed it.

(PS: I have the impression  the labels should be the other way around "Smart Align Vertically" <> "Smart Align Horizontally", but maybe  I'm just confused)

**Comment by megaroeny** [comment]
@BramEsposito sweet thanks!

**Comment by getflourish** [comment]
Merged. Thanks!
