### ISSUE TITLE
Feature request: Batch "Fit Artboard Height"

### ISSUE THREAD

**Issue by mikeprecious** [getflourish/Sketch-Mate#17]
I can select one Artboard and use the Fit Artboard Height ctrl + shift + A command with success.

I can sometimes select two Artboards and use the Fit Artboard Height ctrl + shift + A with success.

At present, if I select a greater number of Artboards, say qty 20, I am unsuccessful with the Fit Artboard Height ctrl + shift + A. 

If the functionality for multiple Artboards is not a confirmed feature, I'd like to submit a request to support batch Fit Artboard Height functionality from this command in Sketch Mate.

Really appreciate the time and effort invested in this Sketch plugin. 

Thanks!

**Comment by getflourish** [comment]
Thanks for your suggestion. I added support to be able to select multiple artboards. :+1:
