### ISSUE TITLE
Duplicate Artboard not duplicating

### ISSUE THREAD

**Issue by megaroeny** [getflourish/Sketch-Mate#24]
When you execute this function, it makes space for an artboard, but doesn't actually duplicate it. See this screencast: 
![2016-05-23 11_25_19](https://cloud.githubusercontent.com/assets/1559447/15475642/11753102-20d9-11e6-8fff-8769a20440d7.gif)

This is on Sketch ~~3.8.1~~ 3.8.3. Thanks!

**Comment by denswor** [comment]
The same issue.

**Comment by jaminroe** [comment]
I got an update for Sketch 3.8.3 😆 Will check if anything's changed.

**Comment by megaroeny** [comment]
@denswor sorry I don't check pull-requests since I don't know how to code them 😆

**Comment by username1290** [comment]
in Github it's very easy: Just go to the pull request and accept it (merge) :)

**Comment by megaroeny** [comment]
No I mean I don't know how to code/program Sketch plugins haha 😃 Just HTML and CSS

**Comment by username1290** [comment]
fast solution: open the file and modify it so it looks like the change in the pull-request

**Comment by megaroeny** [comment]
Oops sorry didn't mean to Close. @sogen I'll try that thanks (for now)

**Comment by milosmilikic** [comment]
Is there a chance for this to be fixed soon?

**Comment by megaroeny** [comment]
@milosmilikic just do what @sogen said. Then it'll be fine. It looks like he already merged the code though and maybe updated. Try downloading the latest version. If not just change that one line of code yourself. It's easy 😉

**Comment by milosmilikic** [comment]
@jaminroe Will try that. Thanks!
