### ISSUE TITLE
Request: Sort Artboard by Position Reversed

### ISSUE THREAD

**Issue by megaroeny** [getflourish/Sketch-Mate#25]
I want to sort my artboards in the Layers panel, so that the top left most artboard on the canvas, is the first artboard at the top of the layers list. Make sense? Thanks! 😄

**Comment by pmerrity** [comment]
This already exists: **Plugins** > **Sketch Mate** > **Sort** > **Reverse Layer Order**

You have to select the layers you want reversed. I would recommend doing them in small groups (no more than 20 artboards). I just tried doing it with 300+ screens and it kept breaking Sketch haha

**Comment by megaroeny** [comment]
Oh, sorry I thought that function would do layers only, not artboards. I'm dumb, I should've just tried it LOL! Thanks man! 👍

**Comment by ovodesign82** [comment]
But how can I sort artboards on layers panel accordingly their positions from left to right? (or from upper_left to bottom_right)
