### ISSUE TITLE
White flashing when using Smart Align

### ISSUE THREAD

**Issue by megaroeny** [getflourish/Sketch-Mate#28]
My Sketch (3.8.3) keeps white flashing the canvas when I'm using the Smart Align Left, Center, Distribute, etc. Doesn't happen with stock/native align functions. **This only happens when you're _not_ at 100% zoom.** Not sure why this would be happening. Thanks

**Comment by megaroeny** [comment]
Updated my description, found when it's specifically happening.

**Comment by RaphyRaph** [comment]
this was a bug in sketch 3.8.\* Fixed in Sketch 39.

**Comment by megaroeny** [comment]
@RaphyRaph ah okay cool. Look forward to the update. I'm on 3.8.3. Updated my description again with version number.

**Comment by megaroeny** [comment]
Fixed in version 39 confirmed. 👌 😄
