### ISSUE TITLE
Smart align top/bottom shortcut conflicts

### ISSUE THREAD

**Issue by salux** [getflourish/Sketch-Mate#3]
The shortcut used for smart align top and smart align bottom conflict with the built-in shortcuts for Move To Front and Move To Back under the Arrange menu.

I kept hitting the shortcut for this only to have my objects jump somewhere unexpectedly and couldn't figure it out until I went spelunking through the plugin shortcuts and figured out what was going on.

**Comment by malfborger** [comment]
@salux In commit 40559723552aa3c23e68ae123b80dd0161cf1859 it has changed to ⌘ + ⌥ + ↓ (control cmd alt + arrowkey). 

I think this also should be added to Smart Align Vertically to keep consistency

**Comment by getflourish** [comment]
I have to admit that managing all those shortcuts is really painful. But I will try to take care of the shortcuts that override the native ones.

**Comment by gogodanny** [comment]
have to uninstall because of smart align conflict : (

**Comment by salux** [comment]
Until the shortcut is changed permanently, you can manually adjust it...
1. In Sketch > Plugins menu > Reveal Plugins Folder...
2. In Finder /Plugins folder > Smart Align > open Smart Align Top.sketchplugin and Smart Align Bottom.sketchplugin using TextEdit or your favorite text editor
3. Change the second line to something other than "control option command {up arrow}" and "control option command {down arrow}" ... I changed "control" to "shift" in my case since there wasn't a conflict that I know of

**Comment by getflourish** [comment]
I finally resolved the conflict. Using ctrl + cmd + arrow keys now.

**Comment by barts** [comment]
Hey when is this update going to make it into Sketch Toolbox? Have been having this issue for a long time and only just recently realized it was because of Sketch Mate.

**Comment by salux** [comment]
Worst case, you can just edit it yourself. The shortcut is at the top of the page for a given plugin. I changed it there and it doesn't conflict anymore. :)

Travis

On May 1, 2015, at 11:11 AM, Bart Szyszka notifications@github.com wrote:

Hey when is this update going to make it into Sketch Toolbox? Have been having this issue for a long time and only just recently realized it was because of Sketch Mate.

**Comment by getflourish** [comment]
@barts Did you uninstall / reinstall the plugin with Toolbox? That should fix the shortcut issues.
