### ISSUE TITLE
Select Parent Group Broken

### ISSUE THREAD

**Issue by ninzucchi** [getflourish/Sketch-Mate#4]
`Select Parent Group` currently does nothing (couple months old bug). Using Sketch 3.2.2 (9983). `Select Group Layers` still works, as does the error message if no layer is selected. Thanks!

Demo : http://recordit.co/7Vnr6voVdE

**Comment by anucreative** [comment]
I've submitted a pull request to fix this: https://github.com/getflourish/Sketch-Mate/pull/5

**Comment by ninzucchi** [comment]
Great, fix works for me thanks.

**Comment by getflourish** [comment]
Thanks, merged :)
