### ISSUE TITLE
Readme on partial install not clear

### ISSUE THREAD

**Issue by tsheiner** [getflourish/Sketch-Mate#45]
I only wanted to install the layer sorting plugins. I tried following instructions in readme but I couldn't make that work/didn't understand.

I ended up opening the the full package contents, deleting what I didn't need and modifying the manifest file. 

This worked but still wondering if there was a simpler way that I just couldn't follow from the instructions.

P.S. Thanks for making these plugins available--very helpful!

**Comment by getflourish** [comment]
Unfortunately, editing the manifest file is the only way to go at the moment. I wish I could split up this repo into single commands and re-bundle them. Maybe in the future!
