### ISSUE TITLE
Readme screenshot links broken

### ISSUE THREAD

**Issue by archetypestudio** [getflourish/Sketch-Mate#47]
I love this plugin and it's really become a great part of my Sketch workflow! I've referenced the screenshots a few times as I started to find more and more stuff I wanted to use. Recently the links started showing as broken. Any chance you could fix those? Thanks again for the great work.

**Comment by getflourish** [comment]
Thanks for reporting. Didn’t realize Dropbox direct links weren’t working anymore. Fixed by hosting the images on CloudApp.
