### ISSUE TITLE
Duplicate Artboard stopped working in Sketch 43

### ISSUE THREAD

**Issue by illustree** [getflourish/Sketch-Mate#48]
Duplicate Artboard shift + ⌘ + D

**Comment by ghost** [comment]
is anyone willing to address this issue ?

**Comment by ghost** [comment]
please...

**Comment by getflourish** [comment]
@edward-battistini Will look into this

**Comment by Heilemann** [comment]
Integral part of my workflow; dying here 😄

**Comment by pkvdesigns** [comment]
You can just use CMD+D to duplicate an artboard to the right. Don't need any plugin for that.
Just make sure you have your artboard selected.

**Comment by Heilemann** [comment]
I specifically want the ability to duplicate and push everything else to the right.

**Comment by Superoutman** [comment]
mark

**Comment by ebattistini** [comment]
The duplicate and push is my key tool 😄 I am missing it a lot right now. Hope you guys find a way.

**Comment by illustree** [comment]
yes ... it's actually only about the pushing the rest to the right

**Comment by girafic** [comment]
@all look in #50

**Comment by illustree** [comment]
@girafic thanks ... you just made my day!

**Comment by philchanet** [comment]
Broken again in Sketch 45, sorry.

**Comment by wwpeng** [comment]
It is also broken for me in Sketch 45. Love this feature, so would love to see a fix here, thanks!

**Comment by gogodanny** [comment]
Broken in Sketch 45 : ( so sad

**Comment by illustree** [comment]
@girafic what we all bought you a coffee and you fixed Mate asap? what's your PayPal? :---)

**Comment by kimballfrank** [comment]
My life is ruined without this incredible plugin

**Comment by sbible** [comment]
Broken in S45. :( My favorite Sketch Mate feature. I use it all the time.

**Comment by getflourish** [comment]
Fixed

**Comment by sbible** [comment]
@getflourish Thanks a ton!

**Comment by philchanet** [comment]
@getflourish Thanks a lot for the fix : )
