### ISSUE TITLE
Misc / Replace Layer stopped working in s45 :---(

### ISSUE THREAD

**Issue by illustree** [getflourish/Sketch-Mate#54]
please can you fix?

**Comment by timdose** [comment]
+1. 

Of all the things that Sketch plugins let us do, this is the one I use the most. In fact, I downgraded to 44.1 immediately once I saw this wasn't working.

**Comment by petelasko** [comment]
This is a hard one to do without.

**Comment by illustree** [comment]
this alt+cmd+R is a MUSTHAVE in sketch ... every version of Sketch it's the first thing I test whether it's still working

**Comment by atillacode** [comment]
Must have indeed. It was a pain over the weekend without "Replace Layer". Started the new week without it, still painful :(

**Comment by ghost** [comment]
Life is pain without this! An update would be very much welcome! Thanks!

**Comment by faithshin1** [comment]
Please fix this! New version Sketch is frustrating to use without your app!

**Comment by illustree** [comment]
@girafic  what we all bought you a coffee and you fixed Mate asap? what's your PayPal? :---)

**Comment by benzai** [comment]
+1 Just updated to Sketch 45 and noticed this doesn't work anymore. It is hard to work in Sketch without this.

**Comment by illustree** [comment]
two workarounds until Mate is back alive:

A. Shift+CMD+V ... then TAB ... then DELETE (Smart mouse users can put that an a macro and Mouse buttons ;---)
B. Automate Sketch Plugin and the command “Layer / Paste and Replace”

**Comment by timdose** [comment]
@getflourish Please see my pull request for a possible fix to this!

**Comment by getflourish** [comment]
Fixed thanks to @timdose
