### ISSUE TITLE
Smart align to parent doesn't work in Sketch 46

### ISSUE THREAD

**Issue by RaphyRaph** [getflourish/Sketch-Mate#60]
smart align vertical
smart align horizontal 

None of these work when selecting a single layer and running the command.

**Comment by pkvdesigns** [comment]
+1

**Comment by Deviad** [comment]
Not even in sketch 4.5.2

**Comment by Mco-Design** [comment]
+1

**Comment by RaphyRaph** [comment]
Use this instead: https://github.com/aparajita/sketch-groupie?ref=sketchhunt

It works on latest Sketch and even can deal with aligning multiple elements within their own parents. A+
