### ISSUE TITLE
Smart Align shortcuts same as Sketch arrange

### ISSUE THREAD

**Issue by megaroeny** [getflourish/Sketch-Mate#7]
So I notice that the shortcuts for Smart Align, a lot of them are the same as Sketch's default shortcuts for Arrange menu items. How can I fix or change this? Should I just change the shortcuts in the plugin files? Thanks

**Comment by RaphyRaph** [comment]
They're supposed to be the same. Smart align will switch between default behavior and smart align depending on the selection. That's what makes it smart.

**Comment by megaroeny** [comment]
Ah okay thanks!
