### ISSUE TITLE
Missing 'Sort' option

### ISSUE THREAD

**Issue by 555** [getflourish/Sketch-Mate#9]
Love this so far but I can't seem to sort items - I've grouped and named my items just like int he example but don't see it in the 'Plugins > Sketch Mate' menu.

![image](https://cloud.githubusercontent.com/assets/197548/9444973/9adaeb64-4a81-11e5-8720-41dd22a8965e.png)

**Comment by chufucious** [comment]
Yep. Would love to know where sort went too!

**Comment by gregwburke** [comment]
I thought I was losing my mind. Any idea on what's going on here?

**Comment by jaylovespie** [comment]
Can't get sort artboards to work for the life of me... This is the biggest thing I wanted from this plug in and I'm so sad this doesn't work!

**Comment by chibicode** [comment]
Same here :(

**Comment by isnav** [comment]
+1

Miss this.

**Comment by guerrero** [comment]
I've created a pull request to show "Sort" menu and its actions, so it solves this issue. Anyway, you should know that Sketch Mate is buggy and therefore some actions doesn't work as expected. There's some alternatives in this [repo](https://github.com/sketchplugins/plugin-directory) that actually do almost all actions that Sketch Mate does.

**Comment by chufucious** [comment]
thanks @guerrero !

**Comment by getflourish** [comment]
Sorting is back. As @guerrero pointed out, with time, a lot of the commands from Sketch Mate have made it into separate and more focused plugins. Sketch Mate will remain my hub for all the commands I need and I hope to inspire others to take the ideas further. Cheers!
